In [11]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [8]:
tracking = pd.read_csv('../data/tracking_week_1.csv')

In [9]:
tracking = tracking[tracking['frameType'].isin(['BEFORE_SNAP','SNAP'])]

features = ['gameId', 'playId','frameId', 'x', 'y', 's', 'a', 'dis', 'o', 'dir']
tracking = tracking[features]
tracking.head()

       gameId  playId  frameId      x      y     s     a   dis       o    dir
0  2022091200      64        1  51.06  28.55  0.72  0.37  0.07  246.17  68.34
1  2022091200      64        2  51.13  28.57  0.71  0.36  0.07  245.41  71.21
2  2022091200      64        3  51.20  28.59  0.69  0.23  0.07  244.45  69.90
3  2022091200      64        4  51.26  28.62  0.67  0.22  0.07  244.45  67.98
4  2022091200      64        5  51.32  28.65  0.65  0.34  0.07  245.74  62.83

In [ ]:
# select play
selected_tracking = tracking[(tracking['gameId'] == 2022091200) & (tracking['playId'] == 64)].sort_values(by='frameId')
selected_tracking.head()

,gameId,playId,frameId,x,y,s,a,dis,o,dir
0,2022091200,64,1,51.06,28.55,0.72,0.37,0.07,246.17,68.34
3423,2022091200,64,1,35.02,22.47,1.25,0.71,0.13,62.74,121.67
1630,2022091200,64,1,41.36,23.75,0.02,0.12,0.00,271.68,301.19
2119,2022091200,64,1,33.97,25.45,0.44,0.50,0.05,209.37,81.95
1793,2022091200,64,1,41.19,30.22,0.12,0.78,0.01,232.87,166.77

In [ ]:
vector = selected_tracking[['x', 'y', 's', 'a', 'dis', 'o', 'dir']]